### ISSUE TITLE
只允许在特定楼中使用折叠功能

### ISSUE THREAD

**Issue by Lhcfl** [Lemon-planting-light/post-folding#3]
- [x] 给话题增加“启用折叠”按钮

- [x] 允许特定标签或特定类别的楼主打开“启用折叠”开关

- [x] 全局允许群组在任意楼打开“启用折叠”开关

- [x] 只有打开了“启用折叠”开关后的话题内的帖子可以折叠

- [x] 关闭了“启用折叠”开关后，原先被折叠的帖子不再被折叠；重新打开后自动恢复

**Comment by senioria** [comment]
后端部分解决.

接口:

- topic对象中增加了folding_enabled字段, 指示该topic中折叠是否启用
- `get /post_foldings/is_folding_enabled?topic=:id`查询对应topic是否已经启用折叠
- `put /post_foldings/set_folding_enabled?topic=:id&enabled=:en`设置该topic是否允许折叠
- `post /post_foldings/toggle_folding_enabled?topic=:id`切换该topic是否允许折叠
